version: '3'
services:
  app:
    image: node:12.6.0
    working_dir: /var/www
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: yarn start
    # command: yarn start
    tty: true
    ports:
      - "3000:3000"
