version: '3'

services:
  node: &app_base
    image: node:12.6.0-alpine
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www 
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    restart: always

  workspace:
    <<: *app_base
    ports:
      - "3000:3000"
    command: yarn dev
